monitor=,preferred,auto,auto

env = XCURSOR_SIZE,24

exec-once = hyprpaper & waybar

input {
    follow_mouse = 1
    sensitivity = -0.9
}

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2

    col.active_border = rgb(89b4fa)
    col.inactive_border = rgb(313244)
    layout = dwindle
}

decoration {
    rounding = 5
    drop_shadow = no
}

animations {
    animation = windows, 1, 7, default
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
    animation = specialWorkspace, 1, 5, default, slidevert
}

master {
    new_is_master = true
}

$mainMod = SUPER

bind = $mainMod, F11, exec, killall -SIGUSR1 waybar

bind=SUPER SHIFT,S,movetoworkspace,special
bind=SUPER,S,togglespecialworkspace,

bind = , XF86AudioLowerVolume, exec, pamixer -d5
bind = , XF86AudioRaiseVolume, exec, pamixer -i5
bind = , XF86AudioMute, exec, pamixer -t

bind = $mainMod, Escape, exec, wlogout -l /home/brian/.config/wlogout/layout --css /home/brian/.config/wlogout/style.css -b4 -c16 -p layer-shell

bind = $mainMod SHIFT, p, exec, slurp | grim -g - - | wl-copy

bind = $mainMod, Q, exec, kitty
bind = $mainMod, G, exec, vivaldi-stable
bind = $mainMod, O, exec, gdlauncher
bind = $mainMod, L, exec, /opt/intellij-idea-ce/bin/idea.sh

bind = $mainMod, SPACE, togglefloating, 
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, J, togglesplit,

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
