[mgr]
keymap = [
	{ on = [ "<Esc>" ], run = "escape" },
	{ on = [ "q" ],     run = "quit" },
    { on = [ "Q" ],     run = "quit --no-cwd-file" },

	{ on = [ "s" ], run = "search rg" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Move to top" },
	{ on = [ "G" ], run = "arrow bot" },
	{ on = [ "w" ], run = "tasks_show" },
	{ on = [ "k" ], run = "arrow -1" },
	{ on = [ "j" ], run = "arrow 1" },
	{ on = [ "h" ], run = [ "leave", "escape --visual --select" ] },
	{ on = [ "l" ], run = [ "enter", "escape --visual --select" ] },

	{ on = [ "d", "d" ], run = [ "remove --permanently --force", "escape --visual --select" ] },

	{ on = [ "v" ], run = "visual_mode" },
	{ on = [ "V" ], run = "visual_mode --unset" },
	{ on = [ "<Space>" ], run = [ "toggle --state=none", "arrow 1" ] },
	{ on = [ "<C-a>" ], run = "toggle_all --state=true" },
	{ on = [ "<C-r>" ], run = "toggle_all --state=none" },

	{ on = [ "o" ], run = "open" },
	{ on = [ "O" ], run = "open --interactive" },
	{ on = [ "y" ], run = [ "yank", "escape --visual --select" ] },
	{ on = [ "x" ], run = [ "yank --cut", "escape --visual --select" ] },
	{ on = [ "p" ], run = "paste" },
	{ on = [ "P" ], run = "paste --force" },
	{ on = [ "a" ], run = "create" },
	{ on = [ "r" ], run = "rename" },
	{ on = [ ";" ], run = "shell --interactive" },
	{ on = [ ":" ], run = "shell --block --interactive" },
	{ on = [ "." ], run = "hidden toggle" },

	{ on = [ "/" ], run = "find --smart" },
	{ on = [ "?" ], run = "find --previous --smart" },
	{ on = [ "n" ], run = "find_arrow" },
	{ on = [ "N" ], run = "find_arrow --previous" },

	{ on = [ "m", "s" ], run = "linemode size",        desc = "Set linemode to size" },
	{ on = [ "m", "p" ], run = "linemode permissions", desc = "Set linemode to permissions" },
	{ on = [ "m", "m" ], run = "linemode mtime",       desc = "Set linemode to mtime" },
	{ on = [ "m", "n" ], run = "linemode none",        desc = "Set linemode to none" },

	{ on = [ "c", "c" ], run = "copy path",             desc = "Copy the absolute path" },
	{ on = [ "c", "d" ], run = "copy dirname",          desc = "Copy the path of the parent directory" },
	{ on = [ "c", "f" ], run = "copy filename",         desc = "Copy the name of the file" },
	{ on = [ "c", "n" ], run = "copy name_without_ext", desc = "Copy the name of the file without the extension" },

	{ on = [ ",", "m" ], run = "sort modified --dir-first",               desc = "Sort by modified time" },
	{ on = [ ",", "M" ], run = "sort modified --reverse --dir-first",     desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "c" ], run = "sort created --dir-first",                desc = "Sort by created time" },
	{ on = [ ",", "C" ], run = "sort created --reverse --dir-first",      desc = "Sort by created time (reverse)" },
	{ on = [ ",", "e" ], run = "sort extension --dir-first",         	   desc = "Sort by extension" },
	{ on = [ ",", "E" ], run = "sort extension --reverse --dir-first",    desc = "Sort by extension (reverse)" },
	{ on = [ ",", "a" ], run = "sort alphabetical --dir-first",           desc = "Sort alphabetically" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse --dir-first", desc = "Sort alphabetically (reverse)" },
	{ on = [ ",", "n" ], run = "sort natural --dir-first",                desc = "Sort naturally" },
	{ on = [ ",", "N" ], run = "sort natural --reverse --dir-first",      desc = "Sort naturally (reverse)" },
	{ on = [ ",", "s" ], run = "sort size --dir-first",                   desc = "Sort by size" },
	{ on = [ ",", "S" ], run = "sort size --reverse --dir-first",         desc = "Sort by size (reverse)" },

	{ on = [ "g", "h" ], run = "cd ~",                     desc = "Go to the home directory" },
	{ on = [ "g", "c" ], run = "cd ~/.dotfiles",           desc = "Go to the dotfiles directory" },
	{ on = [ "g", "d" ], run = "cd ~/Documents",           desc = "Go to the documents directory" },
	{ on = [ "g", "m" ], run = "cd ~/Documents/code/mods", desc = "Go to the mods directory" },

	{ on = [ "z" ],         run = "plugin zoxide",                desc = "Jump to a directory using zoxide" },
	{ on = [ "Z" ],         run = "plugin fzf",                   desc = "Jump to a directory, or reveal a file using fzf" },
]

[select]
keymap = [
	{ on = [ "<Esc>" ],   run = "close" },
	{ on = [ "<Enter>" ], run = "close --submit" },
	{ on = [ "k" ], run = "arrow -1" },
	{ on = [ "j" ], run = "arrow 1" },
]

[input]
keymap = [
    { on = [ "<Backspace>" ], run = "backspace" },
	{ on = [ "<Esc>" ], run = "escape" },
	{ on = [ "<Enter>" ], run = "close --submit" },
	{ on = [ "h" ], run = "move -1" },
	{ on = [ "l" ], run = "move 1" },
	{ on = [ "0" ], run = "move -999" },
	{ on = [ "$" ], run = "move 999" },
	{ on = [ "b" ], run = "backward" },
	{ on = [ "w" ], run = "forward" },
	{ on = [ "e" ], run = "forward --end-of-word" },
	{ on = [ "i" ], run = "insert" },
	{ on = [ "a" ], run = "insert --append" },
	{ on = [ "I" ], run = [ "move -999", "insert" ] },
	{ on = [ "A" ], run = [ "move 999", "insert --append" ] },
	{ on = [ "v" ], run = "visual" },
	{ on = [ "V" ], run = [ "move -999", "visual", "move 999" ] },
	{ on = [ "d" ], run = "delete --cut" },
	{ on = [ "c" ], run = "delete --cut --insert" },
	{ on = [ "x" ], run = [ "delete --cut", "move 1 --in-operating" ] },
	{ on = [ "y" ], run = "yank" },
	{ on = [ "p" ], run = "paste" },
	{ on = [ "P" ], run = "paste --before" },
	{ on = [ "u" ],     run = "undo" },
	{ on = [ "<C-r>" ], run = "redo" }
]

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"
