[manager]
keymap = [
	{ on = [ "<Esc>" ], exec = "escape" },
	{ on = [ "q" ],     exec = "quit" },

	{ on = [ "g", "g" ], exec = "arrow -99999999", desc = "Move to top" },
	{ on = [ "G" ], exec = "arrow 99999999" },
	{ on = [ "w" ], exec = "tasks_show" },
	{ on = [ "k" ], exec = "arrow -1" },
	{ on = [ "j" ], exec = "arrow 1" },
	{ on = [ "h" ], exec = [ "leave", "escape --visual --select" ] },
	{ on = [ "l" ], exec = [ "enter", "escape --visual --select" ] },

	{ on = [ "d", "d" ], exec = [ "remove --permanently --force", "escape --visual --select" ] },

	{ on = [ "v" ], exec = "visual_mode" },
	{ on = [ "V" ], exec = "visual_mode --unset" },
	{ on = [ "<Space>" ], exec = [ "select --state=none", "arrow 1" ] },
	{ on = [ "<C-a>" ], exec = "select_all --state=true" },
	{ on = [ "<C-r>" ], exec = "select_all --state=none" },

	{ on = [ "o" ], exec = "open" },
	{ on = [ "O" ], exec = "open --interactive" },
	{ on = [ "y" ], exec = [ "yank", "escape --visual --select" ] },
	{ on = [ "x" ], exec = [ "yank --cut", "escape --visual --select" ] },
	{ on = [ "p" ], exec = "paste" },
	{ on = [ "P" ], exec = "paste --force" },
	{ on = [ "a" ], exec = "create" },
	{ on = [ "r" ], exec = "rename" },
	{ on = [ ";" ], exec = "shell" },
	{ on = [ ":" ], exec = "shell --block" },
	{ on = [ "." ], exec = "hidden toggle" },

	{ on = [ "/" ], exec = "find --smart" },
	{ on = [ "?" ], exec = "find --previous --smart" },
	{ on = [ "n" ], exec = "find_arrow" },
	{ on = [ "N" ], exec = "find_arrow --previous" },

	{ on = [ "m", "s" ], exec = "linemode size",        desc = "Set linemode to size" },
	{ on = [ "m", "p" ], exec = "linemode permissions", desc = "Set linemode to permissions" },
	{ on = [ "m", "m" ], exec = "linemode mtime",       desc = "Set linemode to mtime" },
	{ on = [ "m", "n" ], exec = "linemode none",        desc = "Set linemode to none" },

	{ on = [ "c", "c" ], exec = "copy path",             desc = "Copy the absolute path" },
	{ on = [ "c", "d" ], exec = "copy dirname",          desc = "Copy the path of the parent directory" },
	{ on = [ "c", "f" ], exec = "copy filename",         desc = "Copy the name of the file" },
	{ on = [ "c", "n" ], exec = "copy name_without_ext", desc = "Copy the name of the file without the extension" },

	{ on = [ ",", "m" ], exec = "sort modified --dir-first",               desc = "Sort by modified time" },
	{ on = [ ",", "M" ], exec = "sort modified --reverse --dir-first",     desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "c" ], exec = "sort created --dir-first",                desc = "Sort by created time" },
	{ on = [ ",", "C" ], exec = "sort created --reverse --dir-first",      desc = "Sort by created time (reverse)" },
	{ on = [ ",", "e" ], exec = "sort extension --dir-first",         	   desc = "Sort by extension" },
	{ on = [ ",", "E" ], exec = "sort extension --reverse --dir-first",    desc = "Sort by extension (reverse)" },
	{ on = [ ",", "a" ], exec = "sort alphabetical --dir-first",           desc = "Sort alphabetically" },
	{ on = [ ",", "A" ], exec = "sort alphabetical --reverse --dir-first", desc = "Sort alphabetically (reverse)" },
	{ on = [ ",", "n" ], exec = "sort natural --dir-first",                desc = "Sort naturally" },
	{ on = [ ",", "N" ], exec = "sort natural --reverse --dir-first",      desc = "Sort naturally (reverse)" },
	{ on = [ ",", "s" ], exec = "sort size --dir-first",                   desc = "Sort by size" },
	{ on = [ ",", "S" ], exec = "sort size --reverse --dir-first",         desc = "Sort by size (reverse)" },

	{ on = [ "g", "h" ], exec = "cd ~",           desc = "Go to the home directory" },
	{ on = [ "g", "c" ], exec = "cd ~/.config",   desc = "Go to the config directory" },
	{ on = [ "g", "d" ], exec = "cd ~/Documents", desc = "Go to the documents directory" },
	{ on = [ "g", "t" ], exec = "cd /tmp",        desc = "Go to the temporary directory" },
]

[select]
keymap = [
	{ on = [ "<Esc>" ],   exec = "close" },
	{ on = [ "<Enter>" ], exec = "close --submit" },
	{ on = [ "k" ], exec = "arrow -1" },
	{ on = [ "j" ], exec = "arrow 1" },
]

[input]
keymap = [
    { on = [ "<Backspace>" ], exec = "backspace" },
	{ on = [ "<Esc>" ], exec = "escape" },
	{ on = [ "<Enter>" ], exec = "close --submit" },
	{ on = [ "h" ], exec = "move -1" },
	{ on = [ "l" ], exec = "move 1" },
	{ on = [ "0" ], exec = "move -999" },
	{ on = [ "$" ], exec = "move 999" },
	{ on = [ "b" ], exec = "backward" },
	{ on = [ "w" ], exec = "forward" },
	{ on = [ "e" ], exec = "forward --end-of-word" },
	{ on = [ "i" ], exec = "insert" },
	{ on = [ "a" ], exec = "insert --append" },
	{ on = [ "I" ], exec = [ "move -999", "insert" ] },
	{ on = [ "A" ], exec = [ "move 999", "insert --append" ] },
	{ on = [ "v" ], exec = "visual" },
	{ on = [ "V" ], exec = [ "move -999", "visual", "move 999" ] },
	{ on = [ "d" ], exec = "delete --cut" },
	{ on = [ "c" ], exec = "delete --cut --insert" },
	{ on = [ "x" ], exec = [ "delete --cut", "move 1 --in-operating" ] },
	{ on = [ "y" ], exec = "yank" },
	{ on = [ "p" ], exec = "paste" },
	{ on = [ "P" ], exec = "paste --before" },
	{ on = [ "u" ],     exec = "undo" },
	{ on = [ "<C-r>" ], exec = "redo" }
]
