[manager]
layout = [1, 3, 2]
sort_dir_first = true
sort_by = "natural"
sort_reverse = false
show_hidden = true

[preview]
tab_size = 4

[opener]
browser = [{ run = 'vivaldi "$@"', orphan = true }]
nvim = [{ run = 'nvim "$@"', block = true }]
viewnior = [{ run = 'viewnior "$@"', orphan = true }]
zathura = [{ run = 'zathura "$@"', orphan = true }]
unzip = [{ run = 'unzip "$@" -x __M*' }]
untar = [{ run = 'tar xzf "$@"' }]
ripdrag = [{ run = 'ripdrag -a "$@"', orphan = true }]
swww = [{ run = 'swww img "$@" -tcenter', orphan = true }]
swww_pixel = [{ desc = "swww pixel", run = 'swww img "$@" -tcenter -fNearest', orphan = true }]

[open]
rules = [
    {mime = "application/pdf", use = ["zathura", "ripdrag"]},
    {name = "application/video", use = ["browser", "ripdrag"]},
    {mime = "application/zip", use = ["unzip", "ripdrag"]},
    {mime = "*.tar.gz", use = ["untar", "ripdrag"]},
    {mime = "image/*", use = ["viewnior", "swww", "swww_pixel", "browser", "ripdrag"]},
    {name = "*.html", use = ["browser", "nvim", "ripdrag"]},
	{name = "*/", use = ["nvim", "ripdrag"]},
	{name = "*", use = ["nvim", "ripdrag"]}
]
