[manager]
layout = [1, 3, 2]
sort_dir_first = true
sort_by = "natural"
sort_reverse = false
show_hidden = true

[preview]
tab_size = 4

[opener]
browser = [{ exec = 'vivaldi "$@"', orphan = true }]
nvim = [{ exec = 'nvim "$@"', block = true }]
viewnior = [{ exec = 'viewnior "$@"', orphan = true }]
zathura = [{ exec = 'zathura "$@"', orphan = true }]
unzip = [{ exec = 'unzip "$@" -x __M*' }]
ripdrag = [{ exec = 'ripdrag -a "$@"', orphan = true }]

[open]
rules = [
    {mime = "application/pdf", use = ["zathura", "ripdrag"]},
    {name = "application/video", use = ["browser", "ripdrag"]},
    {mime = "application/zip", use = ["unzip", "ripdrag"]},
    {mime = "image/*", use = ["viewnior", "browser", "ripdrag"]},
    {name = "*.html", use = ["browser", "nvim", "ripdrag"]},
	{name = "*/", use = ["nvim", "ripdrag"]},
	{name = "*", use = ["nvim", "ripdrag"]}
]
