gesture swipe up 3 hyprctl dispatch togglespecialworkspace d
gesture swipe down 3 hyprctl dispatch togglespecialworkspace d
gesture swipe right 3 hyprctl dispatch workspace -1
gesture swipe left 3 hyprctl dispatch workspace +1
